extraction:
  cpp:
    prepare:
      packages:
      - "libqt5webengine-data"
      - "libqt5svg5-dev"
    configure:
      command:
      - "mkdir build"
      - "cd build"
      - "cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON .."
    index:
      build_command:
      - "cd build"
      - "make"
